export const INTERESTS = [
  'Harry Potter',
  'Dziecko lat 90.',
  'SoundCloud',
  'Spa',
  'Self care',
  'Mężczyzn',
  'Heavy metal',
  'Domówki',
  'Gin z tonikiem',
  'Gimnastyka',
  'Hot yoga',
  'Medytacja',
  'Spotify',
  'Sushi',
  'Domowe treningi',
  'Teatr',
  'Hokej',
  'Koszykówka',
  'Slam poetycki',
  'Chodzenie po kawiarniach',
  'Akwarium',
  'Sneakersy',
  'Instagram',
  'Gorące źródła',
  'Spacery',
  'Bieganie',
  'Podróże',
  'Tandem językowy',
  'Filmy',
  'Gitarzyści',
  'Rozwój społeczny',
  'Siłownia',
  'Media społecznościowe',
  'Hip - hop',
  'Pielęgnacja skóry',
  'J - Pop',
  'Szisza',
  'Krykiet',
  'Freelance',
  'Jazda na deskorolce',
  'Gospel',
  'K - Pop',
  'Fan(ka) Harryego Pottera',
  'Próbowanie nowych rzeczy',
  'Fotografia',
  'Bollywood',
  'Czytanie',
  'Śpiewanie',
  'Sporty Poezja',
  'Stand - up',
  'Kawa',
  'Karaoke',
  'Fortnite',
  'Freediving',
  'Samorozwój',
  'Gotowanie',
  'Ochrona środowiska',
  'Szermierka',
  'Piłka nożna',
  'Gra na saksofonie',
  'Sci - fi',
  'Taniec',
  'Festiwal filmowy',
  'Ogrodnictwo',
  'Szukam',
  'Amatorskie gotowanie',
  'Sauna',
  'Sztuka',
  'Polityka',
  'Flamenco',
  'Muzeum',
  'Nieruchomości',
  'Podcasty',
  'Prawa OzN',
  "Rave'y",
  'Kino samochodowe',
  'Wspinaczka skałkowa',
  'Grill',
  'Piwo kraftowe',
  'Gra na perkusji',
  'Herbata',
  'Gry planszowe',
  'Herbata mrożona',
  'Roblox',
  'Puby',
  'Rock',
  'Tango',
  'Rysowanie',
  'Łamigłówki',
  'Zupa pho',
  'Wolontariat',
  'Ekologia',
  'Jazda na rolkach',
  'Wino',
  'Dungeons & Dragons',
  'Muzyka elektroniczna',
  'Ramen',
  'Podnoszenie ciężarów',
  'Vlogowanie',
  'Muzyka na żywo',
  'Zdrowie psychiczne',
  'Foodie tour',
  'Prawa wyborcze',
  'Jiu - jitsu',
  'Zmiana klimatu',
  'Wystawa',
  'Wyprowadzanie psa',
  'Feminizm',
  'VR roomy',
  'Escape roomy',
  'Zakupy',
  'Brunch',
  'Inwestycje',
  'Skutery wodne',
  'Reggaeton',
  'Ciuchy z second - handu',
  'Jogging',
  'Wycieczki samochodowe',
  'Moda vintage',
  'Voguing',
  'Couchsurfing',
  'Happy hour',
  'Inkluzywność',
  'Muzyka country',
  'Futbol amerykański',
  'Łyżworolki',
  'Tenis',
  'Lody',
  'Wyjście na lodowisko',
  'Prawa człowieka',
  'Wystawy',
  'Pieczeń wieprzowa',
  'Jazda na nartach',
  'Kajakarstwo',
  'Snowboard',
  'Pilates',
  'Pięciobój',
  'Broadway',
  'PlayStation',
  'Cheerleader(ka)',
  'Chór',
  'Taniec na rurze',
  'Piłka nożna pięcioosobowa',
  'Wyścigi samochodowe',
  'Pinterest',
  'Pub quiz',
  'Stoisko z kawą',
  'Bingowanie seriali',
  'Festiwale',
  'Catan',
  'Cosplay',
  'Sporty motorowe',
  'Tworzenie treści',
  'Pisanie piosenek',
  'Malowanie',
  'BodyJam',
  'Paddleboarding',
  'Kręgle',
  'Bodystep',
  'Grime',
  'Brit pop z lat 90.',
  'E - sport',
  'Wyścigi rowerowe',
  'Bodycombat',
  'Tatuaże',
  'Padel',
  'Blackpink',
  'Surfing',
  'Bodypump',
  'Bary na plaży',
  'Paralotniarstwo',
  'Upcycling',
  'Równość',
  'Astrologia',
  'Motocykle',
  'Jazda konna',
  'Przedsiębiorczość',
  'Sake BTS',
  'Podróże z plecakiem',
  'Wędkarstwo',
  'Clubbing',
  'Jedzenie uliczne',
  'Crossfit',
  'Koncerty',
  'Wspinaczka',
  'Pieczenie',
  'Kemping',
  'Blogowanie',
  'Kolekcjonowanie',
  'Samochody',
  'Start - upy',
  'Bubble tea',
  'Licealna liga koszykówki',
  'Badminton',
  'Aktywny tryb życia',
  'Moda',
  'Anime',
  'NBA',
  'MLB',
  'Muzyka funk',
  'Caipirinha',
  'Spędzanie czasu w domu',
  'Tempeh',
  'DIY',
  'Festyny miejskie',
  'Na dworze',
  'TikTok',
  'Piknik',
  'Twitch',
  'Komedia',
  'Trap',
  'Muzyka',
  'Triathlon',
  'Netflix',
  'Disney',
  'Rugby',
  'Tarot',
  'Giełda papierów wartościowych',
  'Akcje',
  'Pływanie',
  'Tenis stołowy',
  'Zabijanie czasu',
  'Trening',
  'Joga',
  'Horrory',
  'Boks',
  'Chill w barze',
  'Komponowanie muzyki',
  'Piesze wędrówki',
  'Gimnastyka artystyczna',
  'Góry',
  'Łucznictwo',
  'Atari',
  'Maraton',
  'Makijaż',
  'Aktywizacja młodzieży',
  'YouTube',
  'Sztuki walki',
  'Marvel',
  'Wegańskie gotowanie',
  'Wermut',
  'Koreańskie jedzenie',
  'Twitter',
  'Siatkówka',
  'Piesze zwiedzanie',
  'Joga vinyasa',
  'Wirtualna rzeczywistość',
  'League of Legends',
  'NFT',
  'Chodzenie po barach',
  'Nintendo',
  'Baseball',
  'Imprezy',
  'Ballet',
  'Zespół muzyczny',
  'Gry online',
  'Tenis plażowy',
  'Nocne życie',
  'Zakupy online',
  'Żeglowanie',
  'Oglądanie gimnastyki olimpijskiej',
  'Gra na basie',
  'Broker internetowy',
  'Militaria',
  'Memy',
  'Among Us',
  'Wyścigi motocyklowe',
  'Metaverse',
  'A capella',
  'Instrumenty muzyczne',
];